// AUTO-GENERATED by server/scripts/gen-firmware-config.mjs
// Source: firmware/nobify.config.yaml  —  DO NOT EDIT BY HAND.
#pragma once

// ---- Device ----
#define NB_DEVICE_ID           "esp32-s3-01"
#define NB_DEVICE_NAME         "Lobby Sensor"

// ---- Firmware + OTA ----
#define NB_FW_VERSION          "1.0.0"
#define NB_OTA_ENABLED         1
#define NB_OTA_CHECK_MS        900000
#define NB_OTA_ARDUINO         1
#define NB_OTA_ARDUINO_PASS    ""

// ---- WiFi ----
#define NB_WIFI_SSID           "YOUR_WIFI_SSID"
#define NB_WIFI_PASSWORD       "YOUR_WIFI_PASSWORD"
#define NB_WIFI_HOSTNAME       "nobify-esp32s3"

// ---- Server ----
#define NB_SERVER_URL          "http://192.168.1.10:8787"
#define NB_INGEST_PATH         "/api/ingest"
#define NB_INGEST_KEY          ""
#define NB_POST_INTERVAL_MS    1000
#define NB_HEARTBEAT_MS        15000

// ---- mmWave 24GHz radar ----
#define NB_MMWAVE_UART_RX      18
#define NB_MMWAVE_UART_TX      17
#define NB_MMWAVE_BAUD         256000
#define NB_MMWAVE_MAX_CM       600
#define NB_MMWAVE_MIN_CM       20
#define NB_CLUTTER_SUPPRESS    1
#define NB_BG_CALIB_MS         6000
#define NB_MICRO_MOTION_THRESH 8
#define NB_MOVEMENT_ENABLED    1
#define NB_APPROACH_SPEED_CMS  2
#define NB_LIGHT_ENABLED       1
#define NB_DARK_LUX            5
#define NB_LUX_ADC_GPIO        1

// ---- WiFi CSI presence ----
#define NB_CSI_ENABLED         1
#define NB_CSI_VAR_THRESH      12.0f
#define NB_CSI_WINDOW          32

// ---- LEDs ----  BLUE = WiFi CSI, ORANGE = mmWave
#define NB_LED_WIFI_GPIO       47
#define NB_LED_MMWAVE_GPIO     48
#define NB_LED_WIFI_COLOR      0x1E90FF
#define NB_LED_MMWAVE_COLOR    0xFF8C00
#define NB_LED_BRIGHTNESS      160
#define NB_LED_NEOPIXEL        1

// ---- Display ----
#define NB_DISPLAY_ENABLED     1
#define NB_DISPLAY_WIDTH       240
#define NB_DISPLAY_HEIGHT      320
#define NB_DISPLAY_ROTATION    1
